- .gitignore
- app/build.gradle.kts
- app/google-services.json
- app/src/main/kotlin/us/wedemy/eggeum/android/LoginActivity.kt
- app/src/main/res/layout/activity_login.xml
- app/src/main/res/values/strings.xml
- build.gradle.kts
- design-resource/src/main/res/drawable/ic_google_logo.xml
- gradle/libs.versions.toml
- secrets.defaults.properties
One-Tap Google Login 방식을 사용하였습니다.
API를 호출을 하지 않는 단계인 IdToken 을 가져오는 로직까지 구현하였으며
API 추가 작업 및 JsonParser migration 작업이 완료되고 난 이후에
IdToken 을 통해 구글에서 AccessToken 을 가져오는 로직,
구글에서 받아온 AccessToken 을 서버에 전달하는 로직까지 구현하면 될 것 같습니다.
> Google login 기능 구현

- app/build.gradle.kts
- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/build-logics.kt
- build-logic/src/main/kotlin/plugins.kt
- data/build.gradle.kts
- data/src/main/kotlin/us/wedemy/eggeum/android/data/client/HttpClient.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/client/moshi.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/mapper/NoticeMapper.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/model/notice/NoticeBodyResponse.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/model/notice/NoticeListResponse.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/NoticeRepositoryProvider.kt
- data/src/test/kotlin/us/wedemy/eggeum/android/data/NoticeTest.kt
- domain/CODEOWNERS
- domain/build.gradle.kts
- domain/src/main/kotlin/us/wedemy/eggeum/domain/model/notice/NoticeBody.kt
- domain/src/main/kotlin/us/wedemy/eggeum/domain/model/notice/NoticeList.kt
- domain/src/main/kotlin/us/wedemy/eggeum/domain/repository/NoticeRepository.kt
- domain/src/main/kotlin/us/wedemy/eggeum/domain/usecase/NoticeApi.kt
- domain/src/main/kotlin/us/wedemy/eggeum/domain/util/SuspendCatching.kt
- domain/src/test/kotlin/us/wedemy/eggeum/domain/SuspendCatchingTest.kt
- gradle/libs.versions.toml
- secrets.properties
- settings.gradle.kts
- 작업 늦어서 죄송합니다.
- Notice API를 domain 및 data 레이어에 추가합니다.
- hilt 관리 방식을 convention-plugin으로 마이그레이션합니다.
- jackson을 moshi로 마이그레이션합니다.
API 추가 작업을 어떤 방식으로 진행할지 미리 리뷰해보시는 게 좋을 거 같아 Notice API만 추가 후 PR 올립니다.
> Notice API 추가 및 hilt convention-plugin 등록

- gradle/libs.versions.toml
- main/src/main/AndroidManifest.xml
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/HomeFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/MainActivity.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/MyAccountFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/SearchFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NewCafeAdapter.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NoticeAdapter.kt
기존의 namespace 통일 작업에 의해 발생한 import 관련 에러를 해결하였습니다.
> 메인화면 import error 해결 

- app/src/main/kotlin/us/wedemy/eggeum/android/ui/LoginActivity.kt
- app/src/main/kotlin/us/wedemy/eggeum/android/viewmodel/LoginViewModel.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/LoginLocalDataSource.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/LoginLocalDataSourceProvider.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/LoginRemoteDataSource.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/LoginRemoteDataSourceProvider.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datastore/TokenDataStoreProvider.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/di/DataSourceModule.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/di/DataStoreModule.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/model/login/LoginBodyResponse.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/model/login/SignUpBodyResponse.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/LoginRepositoryProvider.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/login/LoginBody.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/model/login/SignUpBody.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/LoginRepository.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/LoginApi.kt
- onboard/src/main/kotlin/us/wedemy/eggeum/android/onboard/ui/RegisterNicknameFragment.kt
- onboard/src/main/kotlin/us/wedemy/eggeum/android/onboard/viewmodel/OnBoardViewModel.kt
expiresIn type 변경,
닉네임 중복 검사 validation 로직 수정
화면 이동 이벤트가 정상적으로 처리되도록 수정
> 로그인, 회원 가입 관련 bug fix, DataStore 연동

- common/src/main/kotlin/us/wedemy/eggeum/android/common/ui/BaseBottomSheetFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeDetailFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchCafeFragment.kt
- main/src/main/res/layout/fragment_cafe_detail.xml
- main/src/main/res/layout/item_notice_card.xml
- main/src/main/res/navigation/nav_main.xml
바텀 시트 프래그먼트에 3개의 프래그먼트를 연동 및 
탭을 선택했을 때 해당 프래그먼트가 바텀시트에 렌더링 되는지 확인 후 merge
> 메인 화면 expandable-bottomsheet 구현

- common/src/main/kotlin/us/wedemy/eggeum/android/common/ui/BaseAdapter.kt
- common/src/main/kotlin/us/wedemy/eggeum/android/common/ui/BaseRecyclerViewAdapter.kt
- common/src/main/kotlin/us/wedemy/eggeum/android/common/ui/BaseViewHolder.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/CafeImageAdapter.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/CafeMenuAdapter.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NewCafeAdapter.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/NoticeCardAdapter.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/CafeImageDetailViewHolder.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/CafeImageViewHolder.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/CafeMenuViewHolder.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NewCafeViewHolder.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeCardViewHolder.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeListItemViewHolder.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/CafeImageFragment.kt
- register-cafe/src/main/kotlin/us/wedemy/eggeum/android/registercafe/adapter/CafeImageAdapter.kt
- register-cafe/src/main/kotlin/us/wedemy/eggeum/android/registercafe/adapter/viewholder/CafeImageViewHolder.kt
- register-cafe/src/main/kotlin/us/wedemy/eggeum/android/registercafe/ui/RegisterCafeFragment.kt
RecyclerView 내에 반복되는 코드를 줄이기 위한 Base class 도입 및 적용
> BaseRecyclerAdapter, BaseViewHolder 추가 및 적용

- app/src/main/kotlin/us/wedemy/eggeum/android/ui/IntroActivity.kt
- app/src/main/kotlin/us/wedemy/eggeum/android/viewmodel/IntroViewModel.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/LoginLocalDataSource.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/LoginLocalDataSourceProvider.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datastore/TokenDataStore.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datastore/TokenDataStoreProvider.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/LoginRepositoryProvider.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/LoginRepository.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/LoginApi.kt
자동 로그인 구현
로그아웃 관련 Module Circular Dependency 이슈 등록 후 merge
로그아웃을 하면 로그인 화면으로 돌아옴
로그인할 경우 메인화면으로 돌아옴
로그인했을 때 회원 정보가 없으면 온보딩으로 이동
온보딩이 완료되면 메인화면으로 이동 
모든 모듈(로그인 모듈, 메인모듈, 온보딩 모듈)을 메인 모듈로 병합하면 그 문제를 해결할 수 있으나 피쳐 단위로 모듈화 규칙이 깨지는 문제 
다음 피쳐에서 해결할 예정
> 자동 로그인 구현 

- design-resource/src/main/res/drawable/ic_profile_filled_48.xml
- main/build.gradle.kts
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/item/UserInfo.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/EditMyInfoFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/MyAccountFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/EditMyInfoViewModel.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/MyAccountViewModel.kt
- main/src/main/res/navigation/nav_main.xml
내 정보 화면 수정 화면까지 API 연동 후 merge
ProfileImage 의 UploadFileId 관련 문제 해결 해야 함
> 내 계정 화면 API 연동

- build-logic/build.gradle.kts
- build-logic/src/main/kotlin/build-logics.kt
- common/src/main/kotlin/us/wedemy/eggeum/android/common/util/HorizontalSpacingItemDecoration.kt
- design-resource/src/main/res/values/dimens.xml
- gradle/libs.versions.toml
- main/build.gradle.kts
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/home/HomeFragment.kt
- main/src/main/res/layout/fragment_home.xml
- main/src/main/res/layout/item_notice_card.xml
remote paging (장소 조회, 공지 조회) 구현
local paging (최근 검색어, 최근 방문한 장소) 구현
임시 데이터 추가 된 후 API를 정상적으로 호출하는지, UI에 정상적으로 반영되는지 확인 후 merge 예정
> 페이징 처리 구현 

- common/src/main/kotlin/us/wedemy/eggeum/android/common/util/ToggleAnimation.kt
- login/CODEOWNERS
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/adapter/viewholder/NoticeListItemViewHolder.kt
- navigator/CODEOWNERS
확장/ 축소 애니메이션을 적용할 경우 깜빡거리는 문제가 발생하여 일단은 애니메이션을 비활성화
> 공지 목록 리스트 확장 애니메이션 비활성화

- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/WithdrawFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/WithdrawViewModel.kt
API 가 성공적으로 호출되는 경우에만 로그인 화면으로 이동하는지 확인 후 merge
> 회원 탈퇴 기능 구현 

- app/src/main/AndroidManifest.xml
- update-cafe/src/main/AndroidManifest.xml
- update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeInfoFragment.kt
- update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectOpinionFragment.kt
- update-cafe/src/main/res/layout/fragment_input_cafe_info.xml
- update-cafe/src/main/res/navigation/nav_update_cafe.xml
- update-cafe/src/main/res/values/strings.xml
> 로그인 연동 이후에 작업을 위한 merge 요청

- design-resource/src/main/res/drawable/ic_network_error_100.xml
- main/src/main/AndroidManifest.xml
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/NetworkErrorActivity.kt
- main/src/main/res/layout/activity_network_error.xml
- main/src/main/res/values/strings.xml
- 네트워크 에러 화면 구성
TODO: 각 모듈에서 어떻게 NetworkError 화면을 호출할 것인지, 네트워크 에러 화면에서 다시시도는 어떤식으로 구현해야할 것인지 고민
> 네트워크 에러 화면 구성

- gradle/libs.versions.toml
- update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/InputCafeMenuFragment.kt
- update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/SelectCafeMenuFragment.kt
- update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/UpdateMenuCompleteFragment.kt
- update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/viewmodel/ProposeCafeInfoViewModel.kt
- 지도에서 인텐트 사용을 위해 PR
- 반영
- SelectCafeMenuFragment.kt api 호출 StateFlow로 관리  
- 미반영
- ProductEntity, val 선언 후 .copy()가 동작하지 않아 반영 못함.
- UI에서 변수로 관리하는 부분, 뷰모델에서 관리 (인텐트 작업 후, 할 예정)
- 중복 문자열 리소스로 관리, 문자 값이 아니라 숫자로 보여서 반영 못함.
> 정보수정제안, 피드백 일부 반영 (전체 X)

- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSource.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/datasource/place/remote/PlaceRemoteDataSourceImpl.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/paging/PlacePagingSource.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/repository/PlaceRepositoryImpl.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/service/PlaceService.kt
- data/src/main/kotlin/us/wedemy/eggeum/android/data/service/TokenAuthenticator.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/repository/PlaceRepository.kt
- domain/src/main/kotlin/us/wedemy/eggeum/android/domain/usecase/PlaceUseCase.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/search/SearchFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/CafeDetailViewModel.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/SearchViewModel.kt
검색 화면 2.5km 내에 장소만 마커로 보이도록 설정 
Token Authenticator 내에 token 삭제 로직 주석처리
> 장소 검색 API distance(반경) 반영 

- app/src/main/kotlin/us/wedemy/eggeum/android/IntroActivity.kt
- app/src/main/res/values/themes.xml
- common/src/main/kotlin/us/wedemy/eggeum/android/common/base/BaseActivity.kt
- gradle/libs.versions.toml
- login/src/main/kotlin/us/wedemy/eggeum/android/login/LoginActivity.kt
- main/build.gradle.kts
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/MainActivity.kt
- main/src/main/res/layout/item_cafe_image_detail.xml
- register-cafe/build.gradle.kts
- register-cafe/src/main/kotlin/us/wedemy/eggeum/android/registercafe/ui/RegisterCafeActivity.kt
- update-cafe/build.gradle.kts
- update-cafe/src/main/kotlin/us/wedemy/eggeum/android/updatecafe/ui/UpdateCafeActivity.kt
- Navigation Bar 영역에 버튼이 포함되어 버튼과 Navigation Bar의 클릭 영역이 겹치는 이슈 해결
- 지도가 나오는 화면의 Status Bar 의 배경 색상을 투명하게 변경하여 지도가 Status Bar 영역에서도 보이도록 구현
- 스플래시, 로그인 화면 Status Bar 영역의 배경색상과 텍스트, 아이콘의 색상이 비슷해 텍스트, 아이콘이 잘 보이지 않는 이슈 해결
> Window Insets 관련 문제 사항들 수정

- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/NoticeFragment.kt
- main/src/main/kotlin/us/wedemy/eggeum/android/main/viewmodel/NoticeViewModel.kt
- 단, 데이터가 페이지네이션 처리가 되어있기 때문에 현재 까지 받아온 아이템에 대해서만 적용
- 아직 받아오지 않은 아이템일 경우 추가 조치 필요
> 홈 화면 내 공지 아이템을 클릭하면 공지 화면으로 이동해 해당 공지 아이템이 확장되도록 구현

- gradle.properties
- main/src/main/kotlin/us/wedemy/eggeum/android/main/ui/myaccount/WithdrawFragment.kt
- onboard/build.gradle.kts
- onboard/src/main/kotlin/us/wedemy/eggeum/android/onboard/ui/OnboardActivity.kt
- onboard/src/main/kotlin/us/wedemy/eggeum/android/onboard/ui/OnboardPrivacyThirdFragment.kt
- onboard/src/main/kotlin/us/wedemy/eggeum/android/onboard/ui/RegisterAccountFragment.kt
- onboard/src/main/kotlin/us/wedemy/eggeum/android/onboard/viewmodel/OnBoardViewModel.kt
- onboard/src/main/res/layout/fragment_onboard_privacy_third.xml
- onboard/src/main/res/navigation/nav_onboard.xml
- onboard/src/main/res/values/strings.xml
- 제3자 제공 동의 웹뷰 화면 추가 및 연동, 버튼 이벤트 구현
> 개인정보 제3자 제공 동의 웹뷰 연동

- app/proguard-rules.pro
- Resolve #259 
-
|           Before           |           After            |
|:--------------------------:|:--------------------------:|
| <img src="" width="300" /> | <img src="" width="300" /> |
> T-479 (#259)

- build-logic/src/main/kotlin/internal/Constants.kt
> app version up
